# This config file contains any environment-specific settings that may
# be useful for the prod environment. A few fields are required (the ones below), but
# anything else is up to the requirements of the test suite.
#

# The base url for your service
base_url: ""