# This config file contains any environment-specific settings that may
# be useful for running the end-to-end tests on the preprod environment. A
# few fields are required (the ones below), but anything else is up to the
# requirements of the test suite.
#

# The directory to containing the yaml-based test data files. Required.
testdata_dir: "testdata/"

# The base url for your service
base_url: ""