HTTP_OK_CODE = 200
BAD_REQUEST_CODE = 400
UNAUTHORIZED_CODE = 401
FORBIDDEN_CODE = 403
RESOURCE_NOT_FOUND_CODE = 404
INTERNAL_SERVER_ERROR_CODE = 500

BAD_REQUEST_MESSAGE = "BAD REQUEST"
GENERIC_ERROR_MESSAGE = "GENERIC ERROR"

MAKE_VARIABLE_ID = 26
MODEL_VARIABLE_ID = 28
MODEL_YEAR_VARIABLE_ID = 29
BODY_CLASS_VARIABLE_ID = 5

CACHE_NAME = "main_database"
VIN_CACHE_TABLE_NAME = "vin_table"

VIN_SERVICE_BASE_URL = "https://vpic.nhtsa.dot.gov/api"
